### ISSUE TITLE
Failed to activate the open-recent package

### ISSUE THREAD

**Issue by krasnovpro** [Zren/atom-open-recent#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.9.5
**Thrown From**: [open-recent](https://github.com/Zren/atom-open-recent) package, v4.0.0
### Stack Trace

Failed to activate the open-recent package

```
At Cannot read property 'indexOf' of undefined

TypeError: Cannot read property 'indexOf' of undefined
  at OpenRecent.insertCurrentPaths (/Users/oleg/.atom/packages/open-recent/lib/main.coffee:177:26)
  at OpenRecent.init (/Users/oleg/.atom/packages/open-recent/lib/main.coffee:149:6)
  at Object.module.exports.activate (/Users/oleg/.atom/packages/open-recent/lib/main.coffee:306:15)
  at Package.module.exports.Package.activateNow (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -0:24.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ],
    "disabledPackages": [
      "metrics",
      "vim-mode"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet",
      "last-cursor-position",
      "multi-cursor"
    ]
  },
  "open-recent": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
atom-alignment, v0.12.1
atom-jade, v0.3.0
color-picker, v2.0.13
emmet, v2.3.13
file-icon-supplement, v0.8.3
language-apache, v1.3.0
language-nginx, v0.6.1
last-cursor-position, v0.9.0
linter, v1.10.0
linter-jade, v0.3.2
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
minimap-split-diff, v0.2.0
newton-dark-syntax, v1.1.5
newton-dark-ui, v1.0.9
open-recent, v4.0.0
pigments, v0.18.1
save-session, v0.15.7
set-syntax, v0.3.0
ult-terminal, v0.2.0

# Dev
No dev packages
```

**Comment by Zren** [comment]
Riiiight, forgot to [re-add the defaults](https://github.com/Zren/atom-open-recent/compare/ae0203aae965754c83c55d3addcfca79a7f076e6...acc8df0c14f8665deb2622d7b87a2d2097245230?w=1#diff-2e1bb36917ff76ab7308da52bc968501L135) for new users. Migrating worked fine.

**Comment by Zren** [comment]
Fixed in v4.0.1

**Comment by aubreyz** [comment]
Suddenly started getting this error again - had to disable package

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at DB.getData (file:///C:/Users/ablum/.atom/packages/open-recent/lib/main.coffee:9:31)
    at DB.get (file:///C:/Users/ablum/.atom/packages/open-recent/lib/main.coffee:19:13)
    at OpenRecent.init (file:///C:/Users/ablum/.atom/packages/open-recent/lib/main.coffee:159:37)
    at Object.activate (file:///C:/Users/ablum/.atom/packages/open-recent/lib/main.coffee:320:15)
    at Package.activateNow (C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3296735)
    at C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3296147
    at Package.measure (C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3293757)
    at C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3296007
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3295950)
    at PackageManager.activatePackage (C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:382948)
    at C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:382564
    at Config.transactAsync (C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:332212)
    at PackageManager.activatePackages (C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:382514)
    at PackageManager.activate (C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:382064)
    at C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:1:757178
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (C:\Users\ablum\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:1:757663)

**Comment by Zren** [comment]
That's Issue #31
